### PR TITLE
Create 2015-03-20-AMA-with-Coraline-Ada-Ehmke.md

### PR DESCRIPTION
**Pull request by kmanion**

### CODE REVIEW

**Comment by kmanion** [comment]
Did I do the invite code and start/end time right? cc: @zspencer

**Comment by zspencer** [comment]
Yes,e xcept I told you the wrong thing. It's supposed to be `?invitecode=` if you're linking directly to typeform.

**Comment by zspencer** [comment]
oh wait, let me clarify `?invite-code=XXXXX` should be specified on links from social media/email to Apprenticeship.Community. Hard-coding them into the HTML will mean everyone who clicks that link has the same invite-code; which means we can't track

**Comment by zspencer** [comment]
:+1:!

**Comment by zspencer** [comment]
:Tada: :dancers:

**Pull request merged**
