### PR TITLE
Added Storify to events page

### PR DESCRIPTION
**Pull request by kmanion**

### CODE REVIEW

**Comment by zspencer** [comment]
Have you smoke-tested this to ensure it works locally?

**Comment by kmanion** [comment]
What does that mean?

**Comment by zspencer** [comment]
Have you ran the webpage locally to verify the website looks the way you expect?

**Comment by kmanion** [comment]
No, not yet. How do I do that?

**Comment by zspencer** [comment]
You'll have to run it from the command line. We could pair on it when you
get a chance.

**Pull request merged**
