### PR TITLE
Create 2015-03-18-who-should-join.md

### PR DESCRIPTION
**Pull request by kmanion**

### CODE REVIEW

**Comment by kmanion** [comment]
Now I'm questioning whether this is redundant to "who are you?" cc: @zspencer

**Comment by zspencer** [comment]
Maybe? We could always merge the two.

**Comment by zspencer** [comment]
Or we could move the stuff about the dream into this one, and leave just the staff in the other one and rename it to "Who runs this place?" or something.

**Comment by kmanion** [comment]
this should be ready to merge now. cc: @zspencer

**Comment by zspencer** [comment]
:+1: Merge and release at will.

**Pull request merged**
